### ISSUE TITLE
[Request] 能否添加上游 http proxy 的支持

### ISSUE THREAD

**Issue by LazyZhu** [GangZhuo/dohclient#1]
本地Windows一直使用的是 stunnel+TLS 的 http proxy, 能否让 dohclient 直接支持 http proxy。
同理, [http-proxy](https://github.com/GangZhuo/http-proxy) 也需要这样 ;).

**Comment by GangZhuo** [comment]
Fixed on master.  使用 --proxy=http://[username:password@]<ip>:<port> 来指定上游 http proxy 代理。
